version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on $(date)

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - index.html
    - style.css
    - scripts/**       # if you want to include your shell scripts
    - appspec.yml
  discard-paths: no
  base-directory: .
